version: 2
jobs:
  builder:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login into Docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build builder image
          command: docker build -t titusoss/titus-executor-builder hack/builder
      - run:
          name: Push builder image
          command: docker push titusoss/titus-executor-builder
  ci-builder:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login into Docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build builder image
          command: docker build -t titusoss/titus-ci-builder hack/ci-builder
      - run:
          name: Push builder image
          command: docker push titusoss/titus-ci-builder
  test-local:
    docker:
      - image: titusoss/titus-ci-builder
    resource_class: xlarge
    working_directory: /go/src/github.com/Netflix/titus-executor
    steps:
      - checkout
      - run:
          name: Local tests
          command: make test-local
  build:
    machine:
      enabled: true
      docker_layer_caching: true
    resource_class: xlarge
    working_directory: /go/src/github.com/Netflix/titus-executor
    environment:
      - DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
          name: Run build
          command: |
            apt-get update
            apt-get install -y wget build-essential docker-ce ruby ruby-dev ruby-bundler gcc g++ make pkg-config curl
            wget -O go.tar.gz https://dl.google.com/go/go1.10.1.linux-amd64.tar.gz
            tar -C /usr/local -xzf go.tar.gz
            export PATH=$PATH:/usr/local/go/bin
            export GOPATH=/go
            go get -u github.com/alecthomas/gometalinter
            gometalinter --install
            go get -u github.com/kardianos/govendor
            make --debug build
          
#  test:
#    docker:
#      - image: circleci/golang:1.10.1-stretch
#    environment:
#      GOPATH: /go
#    resource_class: xlarge
#    working_directory: /go/src/github.com/Netflix/titus-executor
#    steps:
#      - checkout
#      - run:
#          name: Run tests, and vet
#          command: |
#            export PATH=/go/bin:${PATH}
#            make test-local
#            make validate

workflows:
  version: 2
  build_and_test:
    jobs:
      - builder
      - ci-builder
      - build:
          requires:
           - builder
      - test-local:
          requires:
            - ci-builder
